services:
  worker_base:
    build: ./processing_worker
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]

  grayscale_worker:
    build: ./processing_worker
    container_name: pillow_worker
    command: celery -A app.tasks.celery_app worker -Q default_ops --loglevel=info
    depends_on:
      - worker_base

  rembg_worker:
    build: ./processing_worker
    container_name: rembg_worker
    command: celery -A app.tasks.celery_app worker -Q heavy_ai --loglevel=info
    depends_on:
      - worker_base

  yolo_worker:
    build: ./processing_worker
    container_name: yolo_worker
    command: celery -A app.tasks.celery_app worker -Q vision_ai --loglevel=info
    depends_on:
      - worker_base
