version: '3.8'

# 1. This creates a configuration template anchor named "worker_base"
# It is NOT a container, so Docker won't try to run it.
x-worker-base: &worker_base
  build: ./processing_worker
  entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
  restart: always

services:
  grayscale_worker:
    <<: *worker_base  # 2. This injects the build setup and the entrypoint script here
    container_name: pillow_worker
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "-Q", "default_ops", "--concurrency=1", "--loglevel=info"]

  rembg_worker:
    <<: *worker_base  # 2. This injects the build setup and the entrypoint script here
    container_name: rembg_worker
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "-Q", "heavy_ai", "--concurrency=1","--loglevel=info"]

  yolo_worker:
    <<: *worker_base  # 2. This injects the build setup and the entrypoint script here
    container_name: yolo_worker
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "-Q", "vision_ai", "--concurrency=1", "--loglevel=info"]
