services:
  api:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    container_name: api_gateway
    restart: always
    ports:
      - "80:8000"
    entrypoint: ["/bin/bash", "/app/api_gateway/entrypoint.sh"]
